                                 **************
                                 * NO DMC LIB *
                                 **************
                                  --= FAQ =--


-------------------------------------------------------------------------------

* What to do in case of "error while loading shared libraries: libno_dmc.so:
  cannot open shared object file: No such file or directory", 

  This error can occur in two main situation when you try to run your program
  which use the NO_DMC_LIB:
  1) Make sure the library is compiled (libno_dmc.so should exist) and be
     readable (in a path that you can access).
  2) Make sure your LD_LIBRARY_PATH env variable is pointing to that path.
     $> export LD_LIBRARY_PATH=/your_path/lib

-------------------------------------------------------------------------------

* What to do in case of "ERROR while trying to open METADATA file:"?

  This is the most usual error, which indicate that your DMC object has no
  metadata attached to it.
  To solve this, you have to generate them, executing the python script using as
  argument the object name:

  # Supposed your object name is like (fullpath): "/my_path/my_obj"
  $> python no_dmc_metadata.py -o /my_path/my_obj

  IMPORTANT Requirement: For this function to succeed, it must be called in a
                         valid (initialized) HL2 user environment!
  
-------------------------------------------------------------------------------


